 [package]
name = "test-logger"
version = "0.1.0"
authors = ["aiden01 <liangu@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logger-rs = { git = "https://github.com/Aiden01/logger-rs.git" }
